#!/bin/sh

#CLASSPATH=./build:lib/xerces.jar:lib/xml-apis.jar:lib/xmlParserAPIs.jar
CLASSPATH=$CLASSPATH:./build:udfv.jar:lib/xerces.jar:lib/xml-apis.jar:lib/xmlParserAPIs.jar

java -Xmx768m -cp $CLASSPATH com.udfv.test.RecalcXML $@ 
