#!/bin/sh
#
#   Copyright 2013 Heart Solutions Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

CLASSPATH=./build:lib/xerces.jar:lib/xml-apis.jar:lib/xmlParserAPIs.jar

BASE=`basename $1`
SRCFILE=$1



REMOVE=""
if [ "$2" = "r" ]; then
    shift
    REMOVE="r"
elif [ "$2" = "ri" ]; then
    shift
    REMOVE="ri"
fi
shift

echo 1>&2 "java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $SRCFILE $@ > $BASE.cmpxml1"
java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $SRCFILE $@ > $BASE.cmpxml1


rm -f $BASE.cmpimg
echo 1>&2 "java -Xmx512m -cp $CLASSPATH com.udfv.test.Xml2img $BASE.cmpxml1 $BASE.cmpimg $@"
java -Xmx512m -cp $CLASSPATH com.udfv.test.Xml2img $BASE.cmpxml1 $BASE.cmpimg $@
echo 1>&2 "java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $BASE.cmpimg > $BASE.cmpxmltmp"
java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $BASE.cmpimg > $BASE.cmpxmltmp
echo 1>&2 "java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $BASE.cmpimg > $BASE.cmpxml2"
java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.Img2xml $BASE.cmpimg > $BASE.cmpxml2

#echo 1>&2 "java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.FileNameFix $BASE.cmpxmltmp .cmpimg > $BASE.cmpxml2"
java -Xincgc -Xmx128m -cp $CLASSPATH com.udfv.test.FileNameFix $BASE.cmpxmltmp $BASE.cmpimg $SRCFILE > $BASE.cmpxml2

rm -f $BASE.cmpxmltmp
diff -c $BASE.cmpxml1 $BASE.cmpxml2

if [ "$REMOVE" = "r" ]; then
    rm -f $BASE.cmpxml1 $BASE.cmpimg $BASE.cmpxml2
elif [ "$REMOVE" = "ri" ]; then
    rm -f $BASE.cmpimg
fi

