#!/bin/sh

CLASSPATH=$CLASSPATH:./build:udfv.jar:lib/xerces.jar:lib/xml-apis.jar:lib/xmlParserAPIs.jar

java -Xincgc -Xmx768m -cp $CLASSPATH com.udfv.test.ViewTree $@ 
#jdb -classpath $CLASSPATH com.udfv.test.Img2xml $@ 
